WIP: Testimonials
oma-wc/oma pull request #34
Opened 2021-11-03 12:22 UTC by andershansander

Work in progress, the CSS rules in the testimonial component does not work yet.

The code is a bit messy so not sure I am going the right path with this.

2021-11-03 12:35 UTC, d-Pixie requested changes

2021-11-03 12:35 UTC, d-Pixie commented on components/testimonials/src/index.js
> +      `.size-1200 .testimonial__content {
No, this is from the outside perspective, we are adding the styles to the parent page. You want `.size-1200 oma-testimonial` here.

2021-11-19 11:50 UTC, andershansander commented
I have forgotten to add the option to configure the time between switching content but otherwise this is ready for a review.

2022-01-24 07:56 UTC, d-Pixie commented on components/center/src/index.js
> +} from "../../grid/src/constants";
This shouldn't be like this, right? Shouldn't we depend on the base package and import the constants from there? @ehannes Now you are pulling in files from outside your own tree, that is brittle since a reorganisation of the other library would brak this, without the API changing.

2022-01-24 07:56 UTC, d-Pixie commented on components/center/src/index.js
> +      @media ${DEFAULT_BREAKPOINT_LARGE.breakpoint} {
I think you have misunderstood how to use this feature. The point is that we define the constants, as it was before you changed it, and you can know that there will be three size breakpoints called `size-600`, `size-900` and `size-1200` (and this is not ideal, should probably be called `small`, `medium`, `large` instead, since the actual breakpoint might change).

So this breakpoint would instead be:
```
.size-1200 .center__content {
  grid-column-start: ${columnStartPerScreenSize[3]};
  grid-column-end: ${columnStartPerScreenSize[3] +
  columnSpanPerScreenSize[3]};
}
```
So you don't have to wrap it in a breakpoint, we use the top level classes to avoid having breakpoints in the components.

2022-01-24 07:56 UTC, d-Pixie commented on components/content-switch-fade/src/index.js
> +const childrenClassName = "oma-content-switch-fade";
These are constants, they should be all caps: `CHILDREN_CLASS_NAME` or actually `CHILD_CLASS_NAME` would probably be grammatically better 🙂

2022-01-24 07:56 UTC, d-Pixie commented on components/content-switch/src/index.js
> +    switch (name) {
I would approve of this if you have several attributes that you were watching, in this case it is only one. A guard clause would work better:

```
```

2022-01-24 08:18 UTC, d-Pixie requested changes

2022-01-24 08:18 UTC, d-Pixie commented on components/content-switch/src/index.js
> +  setContentSwitchInterval = () => {
Prefere guard clauses over nesting the entire body in an if:

```
setContentSwitchInterval = () => {
  if (this._switchInterval) { return; }
  
  this._switchInterval = setInterval(
    this.switchContent.bind(this),
    this._millisecondsPerSlide
  );
};
```

2022-01-24 08:18 UTC, d-Pixie commented on components/content-switch/src/index.js
> +  clearContentSwitchInterval = () => {
Same here, refactor to guard clause.

2022-01-24 08:18 UTC, d-Pixie commented on components/content-switch/src/index.js
> +    this.children().forEach((child) => this.observer.observe(child));
This is not very efficient. Try setting a single observer on the parent instead, since the children can't resize unless their parent resizes.

2022-01-24 08:18 UTC, d-Pixie commented on components/grid/src/index.js
> +  [DEFAULT_BREAKPOINT_SMALL.breakpoint]: DEFAULT_BREAKPOINT_SMALL.className,
I think we should export `small`, `medium`, `large`, `landscape` and `portrait` from state constants and use them both here and in the new component. Since shared names are supposed to be shared through that library component, not like this.

2022-01-24 08:18 UTC, d-Pixie commented on components/grid/src/index.js
> +  [DEFAULT_BREAKPOINT_SMALL.breakpoint]: DEFAULT_BREAKPOINT_SMALL.className,
And revert to the previous format here, except for importing the classnames from State.

2022-02-01 13:26 UTC, andershansander commented on components/center/src/index.js
> +  const closestCenterableColumnCount = (preferredColumnCount) => {
I guess since we should be working with integers here I can at least simplify the logic some. =) No need for the use of floor, ceil and round functions really.

2022-02-01 14:12 UTC, andershansander commented on components/center/src/index.js
> +      @media ${DEFAULT_BREAKPOINT_LARGE.breakpoint} {
Ah, I see, that's good. In that case I can remove the DEFAULT_BREAKPOINT-constants and change the code back as it was before.

2022-02-01 14:17 UTC, andershansander commented on components/center/src/index.js
> +} from "../../grid/src/constants";
I can change this back to how it was before. The constants are not needed if I implement the breakpoints in the center-component like you suggest.

2022-02-01 14:25 UTC, andershansander commented on components/grid/src/index.js
> +  [DEFAULT_BREAKPOINT_SMALL.breakpoint]: DEFAULT_BREAKPOINT_SMALL.className,
Sounds good. I can change this back to how it was before. The constants are not needed if I implement the breakpoints in the center-component like you suggest.

2022-02-03 12:21 UTC, andershansander commented on components/content-switch/src/index.js
> +  setContentSwitchInterval = () => {
Fixed.

2022-02-03 12:21 UTC, andershansander commented on components/content-switch/src/index.js
> +  clearContentSwitchInterval = () => {
Fixed.

2022-02-03 12:24 UTC, andershansander commented on components/center/src/index.js
> +  const closestCenterableColumnCount = (preferredColumnCount) => {
Simplified the code a bit.

2022-05-12 12:32 UTC, d-Pixie approved these changes

2022-05-12 12:32 UTC, d-Pixie commented on components/center/src/useWindowSize.js
> +import { useState, useEffect } from "haunted";
But it's not critical before we merge, can do it next time we need it.

2022-05-12 12:32 UTC, d-Pixie commented on components/content-switch-fade/src/index.js
> +    transition: opacity 400ms ease-in-out;
Transition time feels like something we want to put in a prop 🙂  But also not critical before merge...

2022-05-13 09:04 UTC, merged