New oma-google-calendar component
oma-wc/oma pull request #39
Opened 2022-05-18 13:42 UTC by andershansander

New **oma-google-calendar** component that is used and styled like this:

```
<style>
  oma-google-calendar::part(calendar) {
    display: grid;
    column-gap: 12px;
    row-gap: 12px;
    grid-template-columns: repeat(5, 1fr);
  }
 
  oma-google-calendar::part(event) {
    border: 1px solid royalblue;
    height: 100px;
    padding: 12px;
  }
</style>
<h1>Google Calendar component</h1>
<oma-google-calendar
  api-key="RESTRICTED_BUT_PUBLIC_API_KEY"
  calendar-id="sv.swedish#holiday@group.v.calendar.google.com"
  time-min="2022-05-18T13:40:54.144Z"
  time-max="2022-06-17T13:40:54.144Z"
></oma-google-calendar>
```

2022-05-20 06:46 UTC, ehannes requested changes
Great job! Looking very good in my opinion. Looking forward to start using it and see what it's like working with :smile:

2022-05-20 06:46 UTC, ehannes commented on components/google-calendar/src/helpers.js
> +        ${html`
Currently, we get descriptions like this:
```
Helgdag<br>Om du vill dölja helgdagar går du till Google Kalender-inställningarna &gt; Helgdagar i Sverige
```
So we need to read the descriptions as HTML. I guess that's what we are trying to do with this `${html` call here but unfortunately it's not working.

2022-05-20 06:46 UTC, ehannes commented on components/google-calendar/src/helpers.js
> +      ${event.start.dateTime ? timePart(event.start.dateTime) : null}
Wouldn't we need a similar one for end time?

2022-05-20 06:46 UTC, ehannes commented on components/calendar.html
> +      group-events-by="day"
I'm not sure where the problem lies, but if I remove this `group-events-by` attribute, the first event doesn't display any date, even though it should. I checked the logs and the first event actually has a start date, but there's no `part=date` section in the `event`. so there's probably a bug in the code somewhere.

2022-05-20 06:46 UTC, ehannes commented on components/google-calendar/src/index.js
> +import { getEvents } from './events'
Not sure if I like the module name `events` here. Not all concerning events are placed in that module. You have a `renderEvent` in the `helpers` module. Maybe `api` would be a more suitable name, that's what you are incapsulating in that module, isn't it? The API calls. Or maybe `googleCalendar`?

2022-05-20 07:43 UTC, andershansander commented on components/google-calendar/src/index.js
> +import { getEvents } from './events'
I agree, api or googleCalendar is better. Maybe google-calendar-api.js.

2022-05-20 07:44 UTC, andershansander commented on components/calendar.html
> +      group-events-by="day"
Oh ok, I guess I caused it when I did some refactoring and probably missed that the date disappeared from some events. Maybe I should look into unit testing for web components.

2022-05-20 07:45 UTC, andershansander commented on components/google-calendar/src/helpers.js
> +      ${event.start.dateTime ? timePart(event.start.dateTime) : null}
I forgot about that. =) Will add it.

2022-05-20 07:46 UTC, andershansander commented on components/google-calendar/src/helpers.js
> +        ${html`
Hmm, ok. I noticed it worked for some <u>-tags I saw.  I will look into what happens here.

2022-05-20 08:32 UTC, andershansander commented on components/calendar.html
> +      group-events-by="day"
It was caused by this code: `events.map(renderEvent)` in index.js. I had implemented renderEvent like `const renderEvent = (event, showDate = true)`

So the .map call in index.js passed in the index of each event as the second parameter. So showDate ended up being 0, 1, 2, 3, 4 for the events..

2022-05-20 09:06 UTC, andershansander commented on components/google-calendar/src/helpers.js
> +        ${html`
I hate Tagged Template. 😄 When I change it to `html([event.description || ''])` it works. No idea why.. Maybe it is haunted's implementation of html that is to blame and not Tagged Templates though.

2022-05-20 11:37 UTC, andershansander commented on components/google-calendar/src/helpers.js
> +        ${html`
It works as expected. It was just my understanding of tagged templates. :)

2022-08-12 09:16 UTC, ehannes approved these changes

2022-08-12 09:17 UTC, merged