WIP: Menu
oma-wc/oma pull request #46
Opened 2022-10-23 09:03 UTC by ehannes

2022-11-04 07:09 UTC, d-Pixie requested changes

2022-11-04 07:09 UTC, d-Pixie commented on components/menu/src/index.js
> +      <slot name="alternative-items"></slot>
??? Wo0t?

2022-11-04 07:09 UTC, d-Pixie commented on components/menu/src/index.js
> +      <slot name="items"></slot>
This should just be the children? Or can't you do that with custom elements? I don't remember, it has been too long ... 😆

2022-11-04 07:09 UTC, d-Pixie commented on components/menu/src/index.js
> +Menu.observedAttributes = ['align-menus', 'align-buttons']
Looking at how you use this in the example above, `components.html`, that is how you use it. So these are wrong or the example is wrong either way ...

2022-11-07 15:21 UTC, ehannes commented on components/menu/src/index.js
> +      <slot name="alternative-items"></slot>
I used this approach to support different menu structures for the mobile and desktop menu. For instance:

```
<oma-menu>
  <div slot='items'>
    <ul>
      <li>Menu item</li>
    </ul>
  </div>
  <div slot='alternative-items'>
    <details>
      <summary>Menu item</summary>
      This menu has a different structure.
    </details>
  </div>
</oma-menu>
```

Maybe you have a better way of achieving this? :)

2022-11-07 15:21 UTC, ehannes commented on components/menu/src/index.js
> +Menu.observedAttributes = ['align-menus', 'align-buttons']
Currently, these attributes are not used at all. I was hoping to get some help from you with how to use these.

2022-11-09 08:17 UTC, ehannes commented on components/menu/src/index.js
> +      <slot name="alternative-items"></slot>
We can achieve this by just nesting one level down, so let's remove this.

2022-11-09 08:35 UTC, ehannes commented on components/menu/src/index.js
> +Menu.observedAttributes = ['align-menus', 'align-buttons']
Remove these for now.

2022-11-09 08:40 UTC, ehannes commented on components/menu/src/index.js
> +  items.classList.toggle('oma-menu__items--open', open)
Consider doing the open/close in the shadow dom instead.

2022-11-18 13:34 UTC, d-Pixie commented on components/menu/src/index.js
> +    const button = shadowRoot.querySelector('slot[name=button]')
What happened to including the button in the menu like we talked about?

2022-11-20 08:04 UTC, ehannes commented on components/menu/src/index.js
> +    const button = shadowRoot.querySelector('slot[name=button]')
That's a separate PR :) If we can merge this first, I already have a PR open for the button that I can rebase and fix.

2022-11-20 08:18 UTC, merged