Adds hamburger-button
oma-wc/oma pull request #49
Opened 2022-10-28 15:00 UTC by ehannes

Adds a hamburger button that you can use together with for instance `oma-menu`.

2022-10-31 07:11 UTC, d-Pixie requested changes
I think this should be part of them menu, or actually be the meny. The button will never be used in any other circumstance - given that it has a hardcoded appearance - and the full menu functionality is not far from this anyway.

2022-10-31 07:11 UTC, d-Pixie commented on components/hamburger-button/src/index.js
> +        height: 48px; /* Minimum size for buttons according to Lighthouse */
Should be `min-height` in that case.

2022-10-31 07:11 UTC, d-Pixie commented on components/hamburger-button/src/index.js
> +        width: 48px; /* Minimum size for buttons according to Lighthouse */
`min-width`

2022-10-31 07:11 UTC, d-Pixie commented on components/hamburger-button/src/index.js
> +        margin-left: auto; /* Adjust lines to page margin */
That comment means nothing to me...

2022-11-07 15:23 UTC, ehannes commented
As you said before, let's make this the default button component in `oma-menu`. I'll wait adapting this PR until we have merged the menu component.

2022-11-09 08:45 UTC, ehannes commented on components/hamburger-button/src/index.js
> +    element.shadowRoot.querySelector('.hamburger-button')
consider using `querySelector('slot')`

2022-11-09 08:47 UTC, ehannes commented on components/hamburger-button/src/index.js
> +      .hamburger-button--active
```
slot[data-open='true'] {
...
}
```

2022-11-09 08:47 UTC, ehannes commented on components/hamburger-button/src/index.js
> +      button.classList.toggle('hamburger-button--active')
Set `data-open = true`

2022-11-21 09:41 UTC, ehannes commented on components/menu/src/index.js
> +    const button = slotButton
This should of course be renamed!

2022-11-21 09:43 UTC, ehannes commented on components/menu/src/index.js
> +  const button = slotButton
`renderedButton`

2022-11-21 09:47 UTC, d-Pixie requested changes

2022-11-21 09:47 UTC, d-Pixie commented on components/menu/src/index.js
> +  const slotButton = element.querySelector('[slot=button]') !== null
Rename to `has_user_provided_button` or something.

2022-11-21 09:47 UTC, d-Pixie commented on components/menu/src/index.js
> +  const button = slotButton
Rename to `rendered_button`

2022-11-21 09:47 UTC, d-Pixie commented on components/menu/src/index.js
> +        <oma-hamburger-button></oma-hamburger-button>
```
const onClick = () => {
  panel.toggleAttribute('data-open')
}
const button = slotButton ? html`
        <slot name="button" @click="${onClick}></slot>
      `
    : html`
        <oma-hamburger-button @click="${onClick}></oma-hamburger-button>
     `
```

2022-11-21 09:47 UTC, d-Pixie commented on components/menu/src/index.js
> +        <oma-hamburger-button></oma-hamburger-button>
Maybe ... https://lit.dev/docs/v1/components/events/

2022-11-21 09:47 UTC, d-Pixie commented on components/menu/src/index.js
> +    const button = slotButton
Should be able to delete this.

2022-11-21 09:50 UTC, d-Pixie commented on components/menu/src/index.js
> +    const button = slotButton
Generally try to keep the conditional part as small as possible.
```
const button = shadowRoot.querySelector( slotButton ? 'slot[name=button]' : 'oma-hamburger-button')
```

2022-11-24 09:29 UTC, d-Pixie approved these changes

2022-11-28 08:19 UTC, merged