Menu
oma-wc/oma pull request #64
Opened 2024-02-05 11:48 UTC by ehannes

2024-04-11 09:28 UTC, d-Pixie requested changes

2024-04-11 09:28 UTC, d-Pixie commented on components/menu/src/index.js
> +  ) /* 48 is minimum size for buttons according to Lighthouse */
This doesn't work? You want it to parse the element.buttonSize attribute, default to 48 and also enforce that it is at least 48. So you need something like this:

```suggestion
  const parsed_button_size = parseFloat( element.buttonSize )
  const button_size = isNaN(parsed_button_size) || parsed_button_size < 48 ? 48 : parsed_button_size
```

2024-04-11 09:28 UTC, d-Pixie commented on components/menu/src/index.js
> +  const hypotenuseScale = hypotenuse / buttonSize
Why not just use a squached SVG for this? Or something like https://www.youtube.com/watch?v=R00QiudbD4Y

2024-04-11 09:28 UTC, d-Pixie commented on components/menu/src/index.js
> +        min-height: ${buttonSize}px;
Couldn't be skip some of the math above, like the min 48 part, and just do `min-height: 48px; height: ${button_size}` here?

2024-04-11 09:28 UTC, d-Pixie commented on components/menu/src/index.js
> +      aria-expanded="false"
Shouldn't the expanded prop here be based on the expanded state? Now it will always be false.

2024-04-11 09:28 UTC, d-Pixie commented on components/menu/src/index.js
> +  }, [buttonSize])
Hmmm, this looks strange to me. There are already mechanisms in haunted to deal with attributes: https://hauntedhooks.netlify.app/docs/guides/attributes/ Is this needed?

2024-04-11 09:50 UTC, andershansander commented on components/menu/src/index.js
> +  ) /* 48 is minimum size for buttons according to Lighthouse */
I don't think we actually want to enforce 48px as a minimum. Just that the default value is based on the recommendation from Lighthouse. But this code could probably be written to make this clearer.

2024-04-11 10:00 UTC, andershansander commented on components/menu/src/index.js
> +  }, [buttonSize])
I had problems to propagate the attribute to the inner component. But I will experiment and see if I can find a nicer solution to do this.

2024-04-11 10:05 UTC, andershansander commented on components/menu/src/index.js
> +  }, [buttonSize])
Hmm, it worked fine to propagate the attribute. Not sure why I couldn't get it to work earlier :)

2024-04-11 10:05 UTC, andershansander commented on components/menu/src/index.js
> +  }, [buttonSize])
The code is now simplified a bit.

2024-04-18 11:54 UTC, ehannes commented on components/menu/src/index.js
> +  ) /* 48 is minimum size for buttons according to Lighthouse */
I've learned that 48 is a very large minimum. Don't know why lighthouse wants that.

* WGAC 2.5.8, level AA, requires 24x24
* WGAC 2.5.5, level AAA, requires 44x44

I would say we should require 24px and default to 44px.

2024-04-19 08:23 UTC, andershansander commented on components/menu/src/index.js
> +  const hypotenuseScale = hypotenuse / buttonSize
That is much better, I have done that now and removed the math.

2024-04-19 08:24 UTC, andershansander commented on components/menu/src/index.js
> +        min-height: ${buttonSize}px;
Math has been removed.

2024-04-19 09:01 UTC, andershansander commented on components/menu/src/index.js
> +  ) /* 48 is minimum size for buttons according to Lighthouse */
This code has now been simplified, and default changed to 44px.

2024-05-06 13:52 UTC, ehannes reviewed
I think it looks really good! I just added a commit which sorted the CSS attributes, to keep it nice and tidy 😄 

Just have a few questions:
- The "With button alignment" example, how is that different? I can't really see any difference and I don't see any `buttonalignment` property in the component... Is that removed?
- The "With custom accessibility label" example has wider lines. Is that on purpose?
- The lines does not cover the full width of the button, which I think makes it hard to align this button with other things on a site. Have you thought about that?

2024-05-08 08:28 UTC, andershansander approved these changes

2024-05-08 08:49 UTC, merged